<a href="https://colab.research.google.com/github/sensein/asd-ai-scoping-review/blob/update-scripts/scripts/PRISMA_pipeline_Fabio/3_local_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import glob
import pandas as pd
# Mount Google Drive
from google.colab import drive as gdrive
import re
import numpy as np
import statistics  # for calculating mean and standard deviation

In [ ]:
gdrive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Define the folder containing the subfolders with CSV files
main_folder = '/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries'

In [ ]:
df_input_file = f'{main_folder}/autism_formatted__controlled_combined_noduplicates.csv'

In [ ]:
df = pd.read_csv(df_input_file)
original_data = df
df

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year,Database,text
0,"""Mommy Blogs"" and the Vaccination Exemption Na...",Social media offer an unprecedented opportunit...,"['Internet', 'attitudes', 'health knowledge', ...",10.2196/publichealth.6586,https://pubmed.ncbi.nlm.nih.gov/27876690/,"Tangherlini, Roychowdhury, Glenn, Crespi, Band...",JMIR public health and surveillance,2016.0,PubMed,"Title: ""Mommy Blogs"" and the Vaccination Exemp..."
1,"""Sequencing Matters"": Investigating Suitable A...",Social robots have been shown to be promising ...,"['action selection', 'attention skills', 'auti...",10.3389/frobt.2022.784249,https://pubmed.ncbi.nlm.nih.gov/35356059/,"Baraka, Couto, Melo, Paiva, Veloso",Frontiers in robotics and AI,2022.0,PubMed,"Title: ""Sequencing Matters"": Investigating Sui..."
2,"""Um"" and ""Uh"" Usage Patterns in Children with ...","Pragmatic language difficulties, including unu...","['Autism', 'Disfluency', 'Fillers', 'Natural l...",10.1007/s10803-022-05565-4,https://pubmed.ncbi.nlm.nih.gov/35499654/,"Lawley, Bedrick, MacFarlane, Dolata, Salem, Fo...",Journal of autism and developmental disorders,2023.0,PubMed,"Title: ""Um"" and ""Uh"" Usage Patterns in Childre..."
3,'SenseA'-Autism Early Signs and Pre-Aggressive...,This paper presents an efficient solution for ...,autism early signs; computer vision; feature e...,10.1109/AMS.2017.28,https://www.scopus.com/inward/record.uri?eid=2...,Gamaethige C.; Gunathilake U.; Jayasena D.; Ma...,AMS 2017 - Asia Modelling Symposium 2017 and 1...,2018.0,Scopus,Title: 'SenseA'-Autism Early Signs and Pre-Agg...
4,25th Annual Computational Neuroscience Meeting...,A1 Functional advantages of cell-type heteroge...,NaN,10.1186/s12868-016-0283-6,https://pubmed.ncbi.nlm.nih.gov/27534393/,NaN,BMC neuroscience,2016.0,PubMed,Title: 25th Annual Computational Neuroscience ...
...,...,...,...,...,...,...,...,...,...,...
1832,rs-fMRI Analysis Using Spatio-Temporal Sparse ...,Neuropsychiatric diseases such as Autism Spect...,CNN; Deep Learning; fMRI; Image Processing; Su...,10.1109/SIU55565.2022.9864751,https://www.scopus.com/inward/record.uri?eid=2...,Yener F.M.; Yildiz S.; Hafeez M.A.; Kayasandik...,2022 30th Signal Processing and Communications...,2022.0,Scopus,Title: rs-fMRI Analysis Using Spatio-Temporal ...
1833,rs-fMRI and machine learning for ASD diagnosis...,Autism Spectrum Disorder (ASD) diagnosis is st...,NaN,10.1038/s41598-022-09821-6,https://pubmed.ncbi.nlm.nih.gov/35411059/,"Santana, de Carvalho, Rodrigues, Bastos, de So...",Scientific reports,2022.0,PubMed,Title: rs-fMRI and machine learning for ASD di...
1834,sha-Early Intervention for children at risk of...,Autism Spectrum Disorder (ASD) is a developmen...,Autism Spectrum Disorder; CNN; Cognitive devel...,10.1109/I4Tech55392.2022.9952803,https://www.scopus.com/inward/record.uri?eid=2...,Shetty T.; Zope V.; Dandekar M.; Devnani A.; M...,2022 International Conference on Industry 4.0 ...,2022.0,Scopus,Title: sha-Early Intervention for children at ...
1835,‘Autistic Robots’ for Embodied Emulation of Be...,The goal of this work is to enable interaction...,NaN,10.1007/978-3-319-70022-9_11,https://www.scopus.com/inward/record.uri?eid=2...,Baraka K.; Melo F.S.; Veloso M.,Lecture Notes in Computer Science (including s...,2017.0,Scopus,Title: ‘Autistic Robots’ for Embodied Emulatio...


In [ ]:
"""
autism_words = ['autism', 'pervasive developmental disorder', 'autistic', 'asperger']
ai_words = ['ai', 'artificial intelligence', 'machine learning', 'deep learning', 'machine-learning', 'deep-learning', 'ml', 'dl', 'cluster', 'clustered', 'clustering', 'classify', 'classified', 'classifying', 'classification', 'predict', 'predicted', 'predicting', 'prediction', 'recognize', 'recognized', 'recognizing', 'recognition', 'test', 'tested', 'testing', 'train', 'trained', 'training', 'model', 'modeled', 'modeling', 'supervised learning', 'unsupervised learning', 'reinforcement learning', 'self-supervised learning', 'transfer learning', 'zero-shot learning', 'few-shot learning', 'neural network', 'nn', 'transformer', 'convolutional network', 'convolutional neural network', 'cnn', 'computer vision', 'cv', 'natural language processing', 'nlp', 'audio signal processing', 'audio processing', 'asp', 'large language model', 'language model', 'llm', 'robot', 'robotics', 'agent', 'mining']
behavior_words = ['behavior', 'behave', 'behaved', 'behaving', 'behavioral', 'observation', 'observe', 'observing', 'observed',  'observational', 'pattern', 'response', 'respond', 'responded', 'responding', 'reaction', 'react', 'reacted', 'reacting', 'stereotype', 'stereotypical', 'stereotyped', 'repetitive', 'repeat', 'repeated', 'repeating', 'compulse', 'compulsive', 'tic', 'psychometrics', 'psychometric', 'phenotype', 'phenotypical', 'gaze', 'eye', 'fixation', 'motor', 'move', 'movement', 'moving', 'stand', 'standing', 'stood', 'crawl', 'crawled', 'crawling', 'walk', 'walking', 'walked', 'run', 'ran', 'jump', 'jumped', 'jumping', 'gait', 'locomotion', 'locomotory', 'body', 'posture', 'pose', 'gesture', 'face', 'facial', 'voice', 'speech', 'game', 'play', 'social', 'interaction', 'conversation', 'communication', 'emotion', 'emotional', 'stress', 'anxiety', 'rest', 'relax', 'sleep']
diagnosis_words = ['diagnosis', 'diagnostics', 'diagnostic', 'diagnose', 'diagnosing', 'diagnosed', 'screen', 'screened', 'screening', 'assessment', 'assess', 'assessing', 'assessed', 'detect', 'detection', 'detecting', 'detected']
"""

"\nautism_words = ['autism', 'pervasive developmental disorder', 'autistic', 'asperger']\nai_words = ['ai', 'artificial intelligence', 'machine learning', 'deep learning', 'machine-learning', 'deep-learning', 'ml', 'dl', 'cluster', 'clustered', 'clustering', 'classify', 'classified', 'classifying', 'classification', 'predict', 'predicted', 'predicting', 'prediction', 'recognize', 'recognized', 'recognizing', 'recognition', 'test', 'tested', 'testing', 'train', 'trained', 'training', 'model', 'modeled', 'modeling', 'supervised learning', 'unsupervised learning', 'reinforcement learning', 'self-supervised learning', 'transfer learning', 'zero-shot learning', 'few-shot learning', 'neural network', 'nn', 'transformer', 'convolutional network', 'convolutional neural network', 'cnn', 'computer vision', 'cv', 'natural language processing', 'nlp', 'audio signal processing', 'audio processing', 'asp', 'large language model', 'language model', 'llm', 'robot', 'robotics', 'agent', 'mining']\nbeha

In [ ]:
# after brainstorming, we converged to the following set of words!
autism_words = ['autism', 'pervasive developmental disorder', 'autistic', 'asperger']
ai_words = ['ai', 'artificial intelligence', 'machine learning', 'deep learning', 'machine-learning', 'deep-learning', 'supervised learning', 'unsupervised learning', 'reinforcement learning', 'self-supervised learning', 'transfer learning', 'zero-shot learning', 'few-shot learning', 'neural network', 'convolutional network', 'convolutional neural network', 'cnn', 'computer vision', 'natural language processing', 'audio signal processing', 'audio processing', 'large language model', 'language model', 'robot', 'robotics']
behavior_words = ['behavior', 'behave', 'behaved', 'behaving', 'behavioral', 'observation', 'observe', 'observing', 'observed', 'observational', 'pattern', 'response', 'respond', 'responded', 'responding', 'reaction', 'react', 'reacted', 'reacting', 'psychometrics', 'psychometric', 'phenotype', 'phenotypical', 'stereotype', 'stereotypical', 'stereotyped', 'repetitive', 'repeat', 'repeated', 'repeating', 'compulse', 'compulsive', 'tic', 'gaze', 'eye', 'fixation', 'motor', 'move', 'movement', 'moving', 'stand', 'standing', 'stood', 'crawl', 'crawled', 'crawling', 'walk', 'walking', 'walked', 'run', 'ran', 'running', 'jump', 'jumped', 'jumping', 'gait', 'locomotion', 'locomotory', 'body', 'posture', 'pose', 'gesture', 'face', 'facial', 'voice', 'speech', 'speak', 'talk', 'game', 'play', 'social', 'interaction', 'conversation', 'communication', 'emotion', 'emotional', 'stress', 'anxiety', 'rest', 'relax', 'sleep']
diagnosis_words = ['diagnosis', 'diagnostics', 'diagnostic', 'diagnose', 'diagnosing', 'diagnosed', 'screen', 'screened', 'screening', 'assessment', 'assess', 'assessing', 'assessed', 'detect', 'detection', 'detecting', 'detected']

In [ ]:
#for filter_words in [autism_words, diagnosis_words, ai_words, behavior_words]:
for filter_words in [autism_words, ai_words, behavior_words, diagnosis_words]:

  df = df[
      df['Title'].str.contains('|'.join(fr'\b{word}\b' for word in filter_words), case=False) |
      df['Abstract'].str.contains('|'.join(fr'\b{word}\b' for word in filter_words), case=False) |
      df['Keywords'].str.contains('|'.join(fr'\b{word}\b' for word in filter_words), case=False)
  ]
  print(len(df))

114879
4928
3916
2229


In [ ]:
df.to_csv(f'{main_folder}/autism_ai_behavior_diagnosis_formatted__controlled_combined_noduplicates.csv', index=False)

# EXTRA WORK FOR AUTOMATING THE PROCESS!

In [ ]:
## force removing books' intros
df = df[~df['Abstract'].str.startswith("The proceedings contain ")]
df = df[~df['Title'].str.startswith("Table of contents")]
df = df[~df['Title'].str.contains("Proceedings")]
print(len(df))

2058


In [ ]:
#!pip install transformers

In [ ]:
import torch
from transformers import BertTokenizer, BertModel
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

In [ ]:
tqdm.pandas()

In [ ]:
def compute_embeddings(text):
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    # Flatten the tensor along the batch dimension
    return outputs.last_hidden_state.mean(dim=1).squeeze()

In [ ]:
df['text'] = (
    'Title: ' + df['Title'].astype(str) +
    '\n Abstract: ' + df['Abstract'].astype(str) +
    '\n Keywords: ' + df['Keywords'].astype(str) +
    '\n Authors: ' + df['Authors'].astype(str) +
    '\n Venue: ' + df['Venue'].astype(str) +
    '\n Year: ' + df['Year'].astype(str)
)

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
grouped = df.groupby(['Title', 'Year'])

In [ ]:
def process_group(group):
    # If there's only one item in the group, no need to compute similarity
    if len(group) == 1:
        return []

    embeddings = group['text'].progress_apply(compute_embeddings)
    embeddings_2d = torch.stack(embeddings.to_list()).numpy()
    similarity_matrix = cosine_similarity(embeddings_2d)
    print(similarity_matrix)
    threshold = 0.95 ## SET A GOOD VALUE HERE!!!
    indices_to_drop = set()

    for i in range(len(group)):
        for j in range(i + 1, len(group)):
            if similarity_matrix[i][j] > threshold:
                # Prefer rows with non-null DOI
                if group['DOI'].iloc[i] is not None and pd.notna(group['DOI'].iloc[i]):
                    indices_to_drop.add(group.index[j])
                else:
                    indices_to_drop.add(group.index[i])

    return list(indices_to_drop)

In [ ]:
# Apply the process_group function to each group
indices_to_drop = set()
for name, group in tqdm(grouped):
    indices_to_drop.update(process_group(group))

  0%|          | 3/1833 [00:02<23:13,  1.31it/s]

[[0.9999999 0.9842861]
 [0.9842861 1.0000004]]



  1%|          | 11/1833 [00:04<12:10,  2.49it/s]

[[1.         0.98793435]
 [0.98793435 0.99999964]]



  2%|▏         | 29/1833 [00:06<06:01,  4.99it/s]

[[0.99999976 0.9869848 ]
 [0.9869848  0.9999999 ]]



  2%|▏         | 36/1833 [00:12<10:39,  2.81it/s]

[[0.99999976 0.99637306]
 [0.99637306 1.0000002 ]]



  2%|▏         | 44/1833 [00:17<13:08,  2.27it/s]

[[1.         0.98651373]
 [0.98651373 0.99999994]]



  3%|▎         | 58/1833 [00:20<10:01,  2.95it/s]

[[1.0000001 0.9920135]
 [0.9920135 0.9999998]]



  4%|▍         | 73/1833 [00:23<08:24,  3.49it/s]

[[1.0000001 0.9823731]
 [0.9823731 0.9999999]]



  4%|▍         | 76/1833 [00:24<09:11,  3.19it/s]

[[1.0000002  0.98516226]
 [0.98516226 0.9999999 ]]



  4%|▍         | 80/1833 [00:29<12:42,  2.30it/s]

[[0.9999999  0.96794957]
 [0.96794957 1.0000001 ]]



  5%|▌         | 93/1833 [00:34<12:19,  2.35it/s]

[[1.0000001  0.98896164]
 [0.98896164 0.9999999 ]]



  5%|▌         | 99/1833 [00:37<12:47,  2.26it/s]

[[1.0000001  0.98588836]
 [0.98588836 1.0000002 ]]



  6%|▌         | 105/1833 [00:40<13:38,  2.11it/s]

[[1.0000002 0.9966312]
 [0.9966312 1.0000001]]



  6%|▋         | 116/1833 [00:44<12:05,  2.37it/s]

[[1.        0.9868958]
 [0.9868958 1.0000001]]



  7%|▋         | 124/1833 [00:46<10:47,  2.64it/s]

[[0.9999998  0.98754746]
 [0.98754746 1.        ]]



  8%|▊         | 139/1833 [00:50<09:18,  3.03it/s]

[[1.0000004  0.99898833]
 [0.99898833 0.99999976]]



  8%|▊         | 143/1833 [00:54<11:20,  2.48it/s]

[[1.0000002  0.98643416]
 [0.98643416 0.9999999 ]]



  8%|▊         | 147/1833 [00:56<12:31,  2.24it/s]

[[1.0000001  0.99436307]
 [0.99436307 1.        ]]



  8%|▊         | 150/1833 [01:01<17:22,  1.61it/s]

[[0.9999997 0.9999997]
 [0.9999997 0.9999997]]



  8%|▊         | 153/1833 [01:04<19:13,  1.46it/s]

[[1.0000002  0.9688713 ]
 [0.9688713  0.99999976]]



  9%|▊         | 156/1833 [01:06<18:58,  1.47it/s]

[[1.0000005 0.9848321]
 [0.9848321 1.       ]]



  9%|▉         | 163/1833 [01:08<15:07,  1.84it/s]

[[0.99999976 0.9804732 ]
 [0.9804732  1.0000001 ]]



  9%|▉         | 167/1833 [01:11<15:11,  1.83it/s]

[[1.0000001  0.97801703]
 [0.97801703 1.0000001 ]]



  9%|▉         | 170/1833 [01:12<15:22,  1.80it/s]

[[1.        0.9921313]
 [0.9921313 1.0000001]]



 10%|▉         | 177/1833 [01:16<14:59,  1.84it/s]

[[1.0000002  0.9659205 ]
 [0.9659205  0.99999994]]



 10%|▉         | 178/1833 [01:19<20:54,  1.32it/s]

[[0.9999996  0.9966047 ]
 [0.9966047  0.99999976]]



 10%|▉         | 180/1833 [01:21<22:22,  1.23it/s]

[[1.        0.9968517]
 [0.9968517 1.0000001]]



 10%|▉         | 182/1833 [01:24<23:55,  1.15it/s]

[[1.0000001 0.9810936]
 [0.9810936 0.9999998]]



 10%|█         | 190/1833 [01:26<15:33,  1.76it/s]

[[0.99999994 0.9728738 ]
 [0.9728738  0.99999994]]



 12%|█▏        | 217/1833 [01:29<05:59,  4.50it/s]

[[0.9999999 0.9978799]
 [0.9978799 1.0000001]]



 12%|█▏        | 226/1833 [01:33<07:42,  3.48it/s]

[[0.9999999  0.9703907 ]
 [0.9703907  0.99999994]]



 13%|█▎        | 232/1833 [01:36<08:38,  3.09it/s]

[[1.         0.99357456]
 [0.99357456 1.        ]]



 13%|█▎        | 235/1833 [01:38<09:45,  2.73it/s]

[[1.0000001  0.98199326]
 [0.98199326 0.9999999 ]]



 13%|█▎        | 236/1833 [01:39<11:36,  2.29it/s]

[[0.9999999  0.990101  ]
 [0.990101   0.99999994]]



 14%|█▍        | 261/1833 [01:43<06:04,  4.31it/s]

[[1.0000001  0.99887615]
 [0.99887615 0.9999998 ]]



 15%|█▍        | 274/1833 [01:45<05:28,  4.75it/s]

[[0.9999999 0.9954041]
 [0.9954041 1.       ]]



 15%|█▌        | 277/1833 [01:48<07:53,  3.28it/s]

[[1.0000001 0.9975567]
 [0.9975567 1.0000001]]



 15%|█▌        | 278/1833 [01:53<12:34,  2.06it/s]

[[1.0000001 0.9992702]
 [0.9992702 1.0000001]]



 16%|█▌        | 296/1833 [01:54<07:08,  3.59it/s]

[[1.        0.989818 ]
 [0.989818  0.9999999]]



 16%|█▋        | 298/1833 [01:57<09:00,  2.84it/s]

[[1.0000001  0.9952498 ]
 [0.9952498  0.99999976]]



 17%|█▋        | 311/1833 [01:59<06:36,  3.84it/s]

[[0.9999999 0.9748899]
 [0.9748899 1.       ]]



 17%|█▋        | 314/1833 [02:00<07:28,  3.39it/s]

[[1.0000002  0.9890929 ]
 [0.9890929  0.99999994]]



 17%|█▋        | 315/1833 [02:02<09:45,  2.59it/s]

[[1.0000001 0.9874806]
 [0.9874806 0.9999999]]



 17%|█▋        | 317/1833 [02:06<14:37,  1.73it/s]

[[1.0000001  0.95733607]
 [0.95733607 1.        ]]



 18%|█▊        | 330/1833 [02:09<09:42,  2.58it/s]

[[0.99999976 0.96828854]
 [0.96828854 1.0000001 ]]



 18%|█▊        | 332/1833 [02:11<10:59,  2.27it/s]

[[0.99999976 0.9945282 ]
 [0.9945282  1.0000004 ]]



 18%|█▊        | 334/1833 [02:13<12:49,  1.95it/s]

[[0.99999964 0.9874231 ]
 [0.9874231  1.0000002 ]]



 19%|█▊        | 340/1833 [02:14<10:33,  2.36it/s]

[[1.0000001  0.991837  ]
 [0.991837   0.99999976]]



 19%|█▉        | 346/1833 [02:16<09:17,  2.67it/s]

[[1.0000001 0.9862106]
 [0.9862106 0.9999999]]



 19%|█▉        | 352/1833 [02:18<09:15,  2.67it/s]

[[1.0000001 0.9717344]
 [0.9717344 1.       ]]



 21%|██        | 385/1833 [02:23<04:56,  4.89it/s]

[[0.9999998 0.9499884]
 [0.9499884 0.9999998]]



 21%|██▏       | 392/1833 [02:25<05:25,  4.42it/s]

[[1.0000001  0.97880435]
 [0.97880435 0.9999999 ]]



 22%|██▏       | 405/1833 [02:28<05:20,  4.46it/s]

[[0.99999976 0.9960437 ]
 [0.9960437  1.0000001 ]]



 22%|██▏       | 407/1833 [02:31<07:28,  3.18it/s]

[[1.0000005 0.9987275]
 [0.9987275 0.9999999]]



 22%|██▏       | 408/1833 [02:33<08:55,  2.66it/s]

[[1.0000002 0.9894808]
 [0.9894808 0.9999997]]



 23%|██▎       | 420/1833 [02:37<08:42,  2.71it/s]

[[1.         0.99666953]
 [0.99666953 1.0000001 ]]



 23%|██▎       | 429/1833 [02:40<08:09,  2.87it/s]

[[1.0000002  0.99334157]
 [0.99334157 0.9999999 ]]



 24%|██▎       | 432/1833 [02:42<09:32,  2.45it/s]

[[0.99999976 0.9767316 ]
 [0.9767316  1.0000001 ]]



 24%|██▎       | 434/1833 [02:44<11:27,  2.03it/s]

[[0.99999976 0.9850629 ]
 [0.9850629  1.        ]]



 24%|██▍       | 436/1833 [02:46<13:04,  1.78it/s]

[[1.0000002 0.9980882]
 [0.9980882 1.       ]]



 25%|██▍       | 456/1833 [02:48<05:55,  3.87it/s]

[[0.9999999  0.98496467]
 [0.98496467 0.99999994]]



 25%|██▌       | 459/1833 [02:52<08:32,  2.68it/s]

[[0.99999976 0.9983417 ]
 [0.9983417  1.        ]]



 25%|██▌       | 467/1833 [02:56<08:56,  2.55it/s]

[[0.9999998  0.97817576]
 [0.97817576 1.0000001 ]]



 26%|██▌       | 471/1833 [02:58<09:50,  2.31it/s]

[[1.0000001  0.97536933]
 [0.97536933 1.        ]]



 27%|██▋       | 493/1833 [03:00<05:05,  4.39it/s]

[[0.99999994 0.9841403 ]
 [0.9841403  1.        ]]



 27%|██▋       | 504/1833 [03:02<05:06,  4.34it/s]

[[0.99999976 0.9831063 ]
 [0.9831063  0.99999994]]



 28%|██▊       | 505/1833 [03:05<07:17,  3.03it/s]

[[1.        0.9779373]
 [0.9779373 0.9999996]]



 28%|██▊       | 513/1833 [03:09<07:42,  2.86it/s]

[[0.9999998  0.98678875]
 [0.98678875 0.99999964]]



 28%|██▊       | 515/1833 [03:12<10:07,  2.17it/s]

[[0.9999999  0.97623146]
 [0.97623146 1.0000001 ]]



 28%|██▊       | 518/1833 [03:14<10:54,  2.01it/s]

[[1.         0.98199844]
 [0.98199844 0.99999964]]



 29%|██▊       | 524/1833 [03:16<10:12,  2.14it/s]

[[1.         0.99530673]
 [0.99530673 1.        ]]



 29%|██▉       | 527/1833 [03:18<11:33,  1.88it/s]

[[0.9999999  0.9690881 ]
 [0.9690881  0.99999994]]



 29%|██▉       | 533/1833 [03:21<10:15,  2.11it/s]

[[1.0000002  0.98900306]
 [0.98900306 1.0000001 ]]



 30%|██▉       | 545/1833 [03:23<07:10,  2.99it/s]

[[1.0000001  0.9783951 ]
 [0.9783951  0.99999976]]



 30%|██▉       | 548/1833 [03:27<10:28,  2.04it/s]

[[1.0000002  1.0000002  0.98673415]
 [1.0000002  1.0000002  0.98673415]
 [0.98673415 0.98673415 0.9999999 ]]



 30%|███       | 558/1833 [03:30<08:33,  2.48it/s]

[[0.9999999  0.99550694]
 [0.99550694 1.        ]]



 31%|███       | 560/1833 [03:32<09:53,  2.14it/s]

[[1.        0.9847247]
 [0.9847247 1.0000001]]



 31%|███       | 567/1833 [03:35<09:18,  2.27it/s]

[[0.9999999 0.9967066]
 [0.9967066 0.9999999]]



 31%|███       | 569/1833 [03:37<11:27,  1.84it/s]

[[1.0000004 0.9695281]
 [0.9695281 1.       ]]



 31%|███       | 571/1833 [03:39<13:00,  1.62it/s]

[[0.99999976 0.99285805]
 [0.99285805 1.        ]]



 31%|███▏      | 573/1833 [03:42<16:09,  1.30it/s]

[[1.0000001 0.9835791]
 [0.9835791 1.       ]]



 31%|███▏      | 576/1833 [03:45<16:34,  1.26it/s]

[[1.        0.9844239]
 [0.9844239 1.0000001]]



 33%|███▎      | 598/1833 [03:47<06:03,  3.40it/s]

[[1.         0.97473437]
 [0.97473437 1.0000002 ]]



 33%|███▎      | 608/1833 [03:50<05:44,  3.56it/s]

[[1.         0.96553844]
 [0.96553844 1.0000005 ]]



 33%|███▎      | 610/1833 [03:52<07:00,  2.91it/s]

[[1.0000002  0.98360276]
 [0.98360276 1.0000001 ]]



 34%|███▎      | 616/1833 [03:54<07:13,  2.81it/s]

[[1.0000001  0.99705553]
 [0.99705553 1.        ]]



 34%|███▍      | 629/1833 [03:59<06:49,  2.94it/s]

[[0.99999976 0.9732295 ]
 [0.9732295  1.        ]]



 35%|███▌      | 642/1833 [04:02<05:57,  3.33it/s]

[[0.9999998 0.9395181]
 [0.9395181 0.9999997]]



 35%|███▌      | 648/1833 [04:03<05:42,  3.46it/s]

[[1.0000001 0.9872051]
 [0.9872051 1.       ]]



 36%|███▌      | 662/1833 [04:05<04:16,  4.56it/s]

[[0.9999998 0.9896697]
 [0.9896697 1.0000002]]



 36%|███▋      | 666/1833 [04:07<05:15,  3.70it/s]

[[1.0000004  0.9738718 ]
 [0.9738718  0.99999964]]



 38%|███▊      | 689/1833 [04:09<03:13,  5.91it/s]

[[1.0000002 0.9872577]
 [0.9872577 1.0000002]]



 38%|███▊      | 702/1833 [04:12<03:46,  4.99it/s]

[[1.0000001  0.99374986]
 [0.99374986 1.        ]]



 38%|███▊      | 704/1833 [04:16<05:47,  3.25it/s]

[[1.0000001 0.9858731]
 [0.9858731 1.0000002]]



 39%|███▉      | 717/1833 [04:18<04:25,  4.20it/s]

[[1.0000001 0.9941225]
 [0.9941225 1.0000001]]



 39%|███▉      | 721/1833 [04:20<04:56,  3.75it/s]

[[1.0000001 0.9973228]
 [0.9973228 1.0000005]]



 40%|███▉      | 726/1833 [04:22<05:28,  3.37it/s]

[[0.9999998  0.9883287 ]
 [0.9883287  0.99999976]]



 40%|████      | 737/1833 [04:23<04:28,  4.08it/s]

[[1.0000001 0.9849186]
 [0.9849186 1.0000002]]



 40%|████      | 739/1833 [04:26<06:07,  2.97it/s]

[[1.        0.9639188]
 [0.9639188 1.0000004]]



 41%|████      | 754/1833 [04:30<05:24,  3.33it/s]

[[1.0000001  1.0000001  0.98864317]
 [1.0000001  1.0000001  0.98864317]
 [0.98864317 0.98864317 0.9999998 ]]



 42%|████▏     | 771/1833 [04:34<04:40,  3.79it/s]

[[1.         0.99906284]
 [0.99906284 0.9999999 ]]



 42%|████▏     | 775/1833 [04:35<05:00,  3.53it/s]

[[1.         0.98470944]
 [0.98470944 1.0000001 ]]



 43%|████▎     | 783/1833 [04:38<04:54,  3.56it/s]

[[0.9999999 0.9748969]
 [0.9748969 1.       ]]



 43%|████▎     | 785/1833 [04:39<05:59,  2.91it/s]

[[1.0000001 0.9820052]
 [0.9820052 0.9999998]]



 43%|████▎     | 788/1833 [04:42<06:59,  2.49it/s]

[[1.        0.9776753]
 [0.9776753 0.9999999]]



 43%|████▎     | 790/1833 [04:45<10:20,  1.68it/s]

[[1.        0.9727297]
 [0.9727297 0.9999999]]



 43%|████▎     | 793/1833 [04:49<12:52,  1.35it/s]

[[1.0000004  0.98088   ]
 [0.98088    0.99999994]]



 43%|████▎     | 795/1833 [04:52<14:19,  1.21it/s]

[[1.0000002 0.981028 ]
 [0.981028  1.       ]]



 45%|████▌     | 830/1833 [04:54<03:33,  4.70it/s]

[[1.        0.9813545]
 [0.9813545 0.9999997]]



 46%|████▌     | 835/1833 [04:56<03:57,  4.20it/s]

[[1.        0.9799789]
 [0.9799789 1.0000002]]



 46%|████▌     | 838/1833 [04:58<04:31,  3.67it/s]

[[1.0000005 0.9945049]
 [0.9945049 1.0000002]]



 46%|████▌     | 844/1833 [05:01<05:27,  3.02it/s]

[[1.0000001  0.99069446]
 [0.99069446 1.0000001 ]]



 47%|████▋     | 865/1833 [05:03<03:15,  4.94it/s]

[[1.        0.9926749]
 [0.9926749 1.0000002]]



 48%|████▊     | 871/1833 [05:05<03:40,  4.36it/s]

[[1.0000007  0.98107064]
 [0.98107064 1.0000002 ]]



 48%|████▊     | 873/1833 [05:07<04:47,  3.34it/s]

[[1.0000001 0.9955726]
 [0.9955726 0.9999999]]



 49%|████▉     | 894/1833 [05:10<03:09,  4.96it/s]

[[1.0000001 0.9985039]
 [0.9985039 1.0000002]]



 49%|████▉     | 896/1833 [05:12<04:14,  3.69it/s]

[[1.0000001  0.98532736]
 [0.98532736 1.0000001 ]]



 49%|████▉     | 898/1833 [05:14<05:06,  3.05it/s]

[[1.0000001  0.99053586]
 [0.99053586 1.0000001 ]]



 50%|█████     | 922/1833 [05:16<02:55,  5.18it/s]

[[1.0000002 0.9955932]
 [0.9955932 1.       ]]



 50%|█████     | 925/1833 [05:21<04:41,  3.22it/s]

[[0.99999994 0.97666067]
 [0.97666067 0.9999999 ]]



 51%|█████▏    | 940/1833 [05:24<04:12,  3.53it/s]

[[1.0000001  0.9908893 ]
 [0.9908893  0.99999976]]



 52%|█████▏    | 945/1833 [05:26<04:27,  3.33it/s]

[[1.         0.99200046]
 [0.99200046 0.99999994]]



 52%|█████▏    | 950/1833 [05:28<04:20,  3.39it/s]

[[0.99999994 0.99259734]
 [0.99259734 1.0000001 ]]



 52%|█████▏    | 955/1833 [05:30<05:01,  2.91it/s]

[[0.99999994 0.9524265 ]
 [0.9524265  1.        ]]



 53%|█████▎    | 973/1833 [05:32<03:10,  4.51it/s]

[[0.9999999  0.98685026]
 [0.98685026 0.9999999 ]]



 54%|█████▍    | 989/1833 [05:34<02:33,  5.48it/s]

[[1.         0.98989934]
 [0.98989934 1.0000001 ]]



 55%|█████▍    | 1000/1833 [05:38<03:02,  4.57it/s]

[[1.0000002  0.9658018 ]
 [0.9658018  0.99999964]]



 55%|█████▍    | 1001/1833 [05:40<04:18,  3.22it/s]

[[1.0000001 0.9885075]
 [0.9885075 1.0000002]]



 55%|█████▍    | 1003/1833 [05:43<05:34,  2.48it/s]

[[1.0000002 0.9760636]
 [0.9760636 1.       ]]



 55%|█████▍    | 1006/1833 [05:45<06:19,  2.18it/s]

[[1.0000002 0.9954856]
 [0.9954856 0.9999998]]



 55%|█████▌    | 1011/1833 [05:48<06:23,  2.14it/s]

[[1.0000002 0.9714987]
 [0.9714987 1.0000001]]



 55%|█████▌    | 1016/1833 [05:50<06:00,  2.27it/s]

[[1.0000005  0.9848001 ]
 [0.9848001  0.99999964]]



 56%|█████▋    | 1035/1833 [05:54<04:18,  3.09it/s]

[[0.99999994 0.99999994 0.98217404]
 [0.99999994 0.99999994 0.98217404]
 [0.98217404 0.98217404 0.99999994]]



 57%|█████▋    | 1039/1833 [05:57<04:59,  2.65it/s]

[[1.         0.98241496]
 [0.98241496 1.0000001 ]]



 57%|█████▋    | 1048/1833 [05:59<04:09,  3.14it/s]

[[1.0000002 0.9814992]
 [0.9814992 1.       ]]



 58%|█████▊    | 1054/1833 [06:00<03:46,  3.43it/s]

[[1.0000001 0.9876628]
 [0.9876628 0.9999999]]



 59%|█████▉    | 1084/1833 [06:02<01:51,  6.71it/s]

[[1.0000002  0.99828583]
 [0.99828583 1.        ]]



 59%|█████▉    | 1086/1833 [06:05<02:39,  4.69it/s]

[[1.0000001  0.97904354]
 [0.97904354 1.        ]]



 60%|█████▉    | 1095/1833 [06:08<03:02,  4.05it/s]

[[1.         0.97236073]
 [0.97236073 0.9999999 ]]



 60%|█████▉    | 1096/1833 [06:11<04:33,  2.70it/s]

[[0.99999964 0.9910366 ]
 [0.9910366  0.9999999 ]]



 61%|██████    | 1109/1833 [06:13<03:24,  3.54it/s]

[[1.        0.9805049]
 [0.9805049 1.       ]]



 61%|██████    | 1112/1833 [06:15<03:58,  3.02it/s]

[[0.99999994 0.98147595]
 [0.98147595 1.0000002 ]]



 61%|██████    | 1116/1833 [06:18<04:42,  2.54it/s]

[[1.        0.958978 ]
 [0.958978  0.9999999]]



 61%|██████    | 1119/1833 [06:19<05:05,  2.34it/s]

[[0.9999997 0.992226 ]
 [0.992226  1.0000002]]



 61%|██████    | 1122/1833 [06:22<05:40,  2.09it/s]

[[0.99999976 0.9827924 ]
 [0.9827924  1.0000001 ]]



 61%|██████▏   | 1123/1833 [06:25<09:08,  1.29it/s]

[[1.         0.97406685]
 [0.97406685 1.0000001 ]]



 61%|██████▏   | 1126/1833 [06:28<09:34,  1.23it/s]

[[0.99999994 0.9882994 ]
 [0.9882994  1.        ]]



 62%|██████▏   | 1134/1833 [06:31<06:25,  1.81it/s]

[[1.0000002 0.9857043]
 [0.9857043 1.0000001]]



 62%|██████▏   | 1143/1833 [06:33<04:40,  2.46it/s]

[[0.9999995  0.98276114]
 [0.98276114 1.0000001 ]]



 64%|██████▎   | 1164/1833 [06:35<02:41,  4.13it/s]

[[1.0000001 0.9735204]
 [0.9735204 1.0000004]]



 64%|██████▍   | 1171/1833 [06:38<03:05,  3.57it/s]

[[1.0000001  0.93479836]
 [0.93479836 0.99999976]]



 64%|██████▍   | 1172/1833 [06:42<04:28,  2.46it/s]

[[1.0000001 0.9859102]
 [0.9859102 1.0000002]]



 65%|██████▌   | 1192/1833 [06:45<02:54,  3.67it/s]

[[1.0000001  0.98667794]
 [0.98667794 0.9999999 ]]



 65%|██████▌   | 1194/1833 [06:47<03:26,  3.09it/s]

[[0.9999997 0.9843494]
 [0.9843494 1.0000002]]



 65%|██████▌   | 1195/1833 [06:48<04:08,  2.57it/s]

[[0.9999999 0.9932288]
 [0.9932288 1.       ]]



 65%|██████▌   | 1197/1833 [06:51<05:19,  1.99it/s]

[[1.         0.98513603]
 [0.98513603 1.0000001 ]]



 66%|██████▌   | 1205/1833 [06:53<04:08,  2.53it/s]

[[1.0000001  0.98149383]
 [0.98149383 1.0000001 ]]



 66%|██████▌   | 1206/1833 [06:55<05:38,  1.85it/s]

[[1.0000002 0.9954549]
 [0.9954549 1.0000002]]



 68%|██████▊   | 1241/1833 [06:59<02:04,  4.75it/s]

[[0.9999998 0.9761865]
 [0.9761865 1.0000004]]



 68%|██████▊   | 1253/1833 [07:02<02:03,  4.69it/s]

[[1.         0.97821456]
 [0.97821456 0.99999976]]



 69%|██████▊   | 1258/1833 [07:05<02:27,  3.91it/s]

[[1.0000002 0.9534515]
 [0.9534515 1.       ]]



 69%|██████▉   | 1267/1833 [07:06<02:16,  4.15it/s]

[[0.9999998 0.9898915]
 [0.9898915 0.9999999]]



 69%|██████▉   | 1268/1833 [07:08<02:48,  3.35it/s]

[[0.99999976 0.9849111 ]
 [0.9849111  0.9999997 ]]



 69%|██████▉   | 1273/1833 [07:10<03:04,  3.04it/s]

[[1.0000001 0.9802337]
 [0.9802337 1.0000002]]



 70%|███████   | 1284/1833 [07:14<03:11,  2.87it/s]

[[1.0000002 0.9348322]
 [0.9348322 1.0000001]]



 70%|███████   | 1287/1833 [07:18<04:07,  2.21it/s]

[[0.99999994 0.99625015]
 [0.99625015 0.99999964]]



 71%|███████   | 1295/1833 [07:20<03:31,  2.54it/s]

[[1.0000002 0.9703113]
 [0.9703113 1.0000002]]



 71%|███████   | 1297/1833 [07:22<04:17,  2.08it/s]

[[1.0000001  0.9838523 ]
 [0.9838523  0.99999994]]



 72%|███████▏  | 1314/1833 [07:25<02:25,  3.58it/s]

[[0.99999994 0.9841248 ]
 [0.9841248  1.0000001 ]]



 73%|███████▎  | 1337/1833 [07:27<01:37,  5.11it/s]

[[0.99999994 0.99838483]
 [0.99838483 0.99999976]]



 73%|███████▎  | 1342/1833 [07:31<02:12,  3.72it/s]

[[1.0000001  0.99074686]
 [0.99074686 0.9999999 ]]



 73%|███████▎  | 1345/1833 [07:34<02:53,  2.81it/s]

[[0.99999994 0.97495323]
 [0.97495323 0.9999999 ]]



 74%|███████▍  | 1358/1833 [07:37<02:27,  3.23it/s]

[[1.0000001 1.0000001]
 [1.0000001 1.0000001]]



 75%|███████▍  | 1367/1833 [07:41<02:30,  3.09it/s]

[[0.9999997  0.99541354]
 [0.99541354 0.9999999 ]]



 75%|███████▍  | 1373/1833 [07:43<02:33,  3.00it/s]

[[1.0000001 0.9817458]
 [0.9817458 1.0000002]]



 75%|███████▌  | 1379/1833 [07:47<03:03,  2.47it/s]

[[0.9999998  0.98242694]
 [0.98242694 1.        ]]



 76%|███████▌  | 1388/1833 [07:50<02:54,  2.55it/s]

[[0.99999976 0.98262036]
 [0.98262036 1.        ]]



 76%|███████▌  | 1392/1833 [07:52<03:10,  2.32it/s]

[[0.9999998  0.98577523]
 [0.98577523 0.9999999 ]]



 76%|███████▋  | 1399/1833 [07:55<02:58,  2.43it/s]

[[1.         0.9750579 ]
 [0.9750579  0.99999994]]



 76%|███████▋  | 1401/1833 [07:58<03:42,  1.94it/s]

[[1.0000001 0.9754382]
 [0.9754382 1.       ]]



 77%|███████▋  | 1416/1833 [08:00<02:19,  2.99it/s]

[[1.0000002  0.97386056]
 [0.97386056 1.0000004 ]]



 78%|███████▊  | 1424/1833 [08:04<02:27,  2.77it/s]

[[1.         0.9837189 ]
 [0.9837189  0.99999994]]



 78%|███████▊  | 1432/1833 [08:07<02:24,  2.77it/s]

[[0.9999999 0.9836361]
 [0.9836361 1.0000004]]



 78%|███████▊  | 1433/1833 [08:09<03:11,  2.09it/s]

[[1.        0.9504783]
 [0.9504783 1.       ]]



 79%|███████▊  | 1441/1833 [08:11<02:35,  2.53it/s]

[[0.9999999  0.98873425]
 [0.98873425 0.9999998 ]]



 79%|███████▉  | 1446/1833 [08:13<02:32,  2.53it/s]

[[1.        0.9903023]
 [0.9903023 1.       ]]



 79%|███████▉  | 1457/1833 [08:16<02:06,  2.97it/s]

[[0.9999999  0.98642933]
 [0.98642933 1.0000005 ]]



 83%|████████▎ | 1514/1833 [08:20<00:41,  7.66it/s]

[[1.         0.97999585]
 [0.97999585 0.99999994]]



 83%|████████▎ | 1516/1833 [08:23<00:56,  5.56it/s]

[[0.99999994 0.9963473 ]
 [0.9963473  0.9999997 ]]



 84%|████████▍ | 1543/1833 [08:25<00:37,  7.64it/s]

[[1.0000002  0.98645526]
 [0.98645526 1.0000002 ]]



 85%|████████▍ | 1553/1833 [08:27<00:43,  6.50it/s]

[[1.         0.97160804]
 [0.97160804 1.        ]]



 85%|████████▍ | 1555/1833 [08:29<00:55,  5.03it/s]

[[0.9999996 0.9769971]
 [0.9769971 1.0000001]]



 85%|████████▍ | 1557/1833 [08:31<01:08,  4.01it/s]

[[1.0000005 0.9843703]
 [0.9843703 1.       ]]



 85%|████████▌ | 1566/1833 [08:35<01:17,  3.44it/s]

[[0.9999999 0.9735658]
 [0.9735658 1.       ]]



 86%|████████▌ | 1580/1833 [08:37<01:02,  4.03it/s]

[[1.0000001 0.9930241]
 [0.9930241 0.9999999]]



 86%|████████▋ | 1581/1833 [08:39<01:19,  3.19it/s]

[[0.99999976 0.98252   ]
 [0.98252    1.        ]]



 87%|████████▋ | 1595/1833 [08:42<01:00,  3.92it/s]

[[1.0000001 0.9782624]
 [0.9782624 0.9999996]]



 88%|████████▊ | 1611/1833 [08:44<00:45,  4.85it/s]

[[0.99999976 0.9815359 ]
 [0.9815359  1.0000004 ]]



 88%|████████▊ | 1617/1833 [08:47<00:53,  4.02it/s]

[[0.9999999  0.96514666]
 [0.96514666 0.9999999 ]]



 89%|████████▉ | 1630/1833 [08:49<00:47,  4.23it/s]

[[1.0000001  0.98737794]
 [0.98737794 0.99999994]]



 89%|████████▉ | 1631/1833 [08:54<01:21,  2.49it/s]

[[0.9999999 0.9753164]
 [0.9753164 1.0000001]]



 90%|████████▉ | 1648/1833 [08:56<00:50,  3.65it/s]

[[1.        0.9811489]
 [0.9811489 0.9999997]]



 90%|█████████ | 1654/1833 [08:58<00:52,  3.43it/s]

[[1.0000002  0.9899511 ]
 [0.9899511  0.99999976]]



 91%|█████████ | 1667/1833 [09:02<00:44,  3.69it/s]

[[0.99999976 0.9980352 ]
 [0.9980352  1.0000004 ]]



 92%|█████████▏| 1681/1833 [09:04<00:37,  4.08it/s]

[[1.0000001  0.9711455 ]
 [0.9711455  0.99999994]]



 92%|█████████▏| 1682/1833 [09:09<00:59,  2.55it/s]

[[1.         0.96705055]
 [0.96705055 1.0000001 ]]



 92%|█████████▏| 1691/1833 [09:11<00:49,  2.88it/s]

[[1.         0.97733134]
 [0.97733134 0.99999976]]



 92%|█████████▏| 1695/1833 [09:13<00:53,  2.56it/s]

[[1.         0.97946906]
 [0.97946906 1.0000001 ]]



 93%|█████████▎| 1709/1833 [09:16<00:37,  3.35it/s]

[[0.9999998 0.9958711]
 [0.9958711 0.9999999]]



 94%|█████████▍| 1719/1833 [09:18<00:29,  3.80it/s]

[[1.0000001 0.9975517]
 [0.9975517 1.0000001]]



 94%|█████████▍| 1722/1833 [09:21<00:39,  2.81it/s]

[[0.9999999 0.9708869]
 [0.9708869 0.9999999]]



 95%|█████████▍| 1737/1833 [09:24<00:28,  3.42it/s]

[[0.9999996 0.9840227]
 [0.9840227 1.0000002]]



 95%|█████████▍| 1738/1833 [09:27<00:39,  2.41it/s]

[[0.9999997 0.9804051]
 [0.9804051 0.9999999]]



 95%|█████████▌| 1746/1833 [09:30<00:32,  2.64it/s]

[[1.0000004  0.98177063]
 [0.98177063 0.9999999 ]]



 95%|█████████▌| 1748/1833 [09:33<00:41,  2.02it/s]

[[1.         0.97153604]
 [0.97153604 1.        ]]



 95%|█████████▌| 1750/1833 [09:35<00:45,  1.82it/s]

[[1.0000004 0.9808438]
 [0.9808438 1.       ]]



 96%|█████████▌| 1754/1833 [09:37<00:43,  1.81it/s]

[[1.         0.98134923]
 [0.98134923 1.0000002 ]]



 96%|█████████▌| 1760/1833 [09:40<00:40,  1.82it/s]

[[1.        0.9916284]
 [0.9916284 1.0000001]]



 96%|█████████▌| 1761/1833 [09:45<01:02,  1.15it/s]

[[1.         0.96233237]
 [0.96233237 1.0000001 ]]



 97%|█████████▋| 1779/1833 [09:49<00:24,  2.20it/s]

[[1.0000002 0.9575016]
 [0.9575016 0.9999999]]



 98%|█████████▊| 1791/1833 [09:52<00:15,  2.80it/s]

[[1.         0.98040354]
 [0.98040354 1.        ]]



 98%|█████████▊| 1804/1833 [09:54<00:08,  3.53it/s]

[[1.0000001  0.9941555 ]
 [0.9941555  0.99999976]]



100%|██████████| 1833/1833 [09:56<00:00,  3.07it/s]

[[1.0000001  0.98411435]
 [0.98411435 1.        ]]


In [ ]:
indices_to_drop

{56,
 74,
 75,
 76,
 77,
 78,
 82,
 83,
 89,
 90,
 94,
 95,
 97,
 99,
 100,
 103,
 104,
 106,
 115,
 116,
 117,
 119,
 120,
 124,
 125,
 127,
 128,
 130,
 131,
 134,
 139,
 143,
 146,
 147,
 149,
 154,
 158,
 160,
 161,
 162,
 165,
 166,
 167,
 168,
 169,
 171,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 181,
 182,
 185,
 187,
 188,
 191,
 193,
 194,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 206,
 207,
 208,
 209,
 210,
 212,
 215,
 216,
 218,
 219,
 220,
 223,
 226,
 227,
 228,
 229,
 231,
 233,
 235,
 236,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 250,
 251,
 252,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 267,
 269,
 270,
 271,
 272,
 277,
 279,
 280,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 292,
 295,
 299,
 300,
 301,
 302,
 303,
 304,
 308,
 309,
 310,
 314,
 316,
 318,
 319,
 320,
 322,
 323,
 325,
 328,
 330,
 331,
 334,
 338,
 339,
 342,
 344,
 347,
 348,
 350,
 351,
 353,
 354,
 356,
 357,
 359,
 360,
 362,
 365,
 366,
 368,
 372,
 373,


In [ ]:
len(indices_to_drop)

221

In [ ]:
df[df['Title']=='Classification of Autism Spectrum Disorder From EEG-Based Functional Brain Connectivity Analysis.']

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year,Database,text
233,Classification of Autism Spectrum Disorder Fro...,Autism is a psychiatric condition that is typi...,"AUTISM spectrum disorders, CHILDREN with autis...",NaN,https://search.ebscohost.com/login.aspx?direct...,"Alotaibi, Noura and Maharatna, Koushik",Neural Computation,2021.0,CINAHL (Exodus),Title: Classification of Autism Spectrum Disor...
240,Classification of Autism Spectrum Disorder Fro...,Autism is a psychiatric condition that is typi...,"AUTISM spectrum disorders, CHILDREN with autis...",NaN,https://search.ebscohost.com/login.aspx?direct...,"Alotaibi, Noura and Maharatna, Koushik",Neural Computation,2021.0,CINAHL (Exodus),Title: Classification of Autism Spectrum Disor...
899,Classification of Autism Spectrum Disorder Fro...,Autism is a psychiatric condition that is typi...,NaN,10.1162/neco_a_01394,https://pubmed.ncbi.nlm.nih.gov/34411269/,"Alotaibi, Maharatna",Neural computation,2021.0,PubMed,Title: Classification of Autism Spectrum Disor...


In [ ]:
# Drop identified duplicate indices
df = df.drop(list(indices_to_drop)).reset_index(drop=True)


In [ ]:
'''
df = df.sort_values(by='DOI', ascending=False)
df = df.drop_duplicates(subset=['Title', 'Year', 'Venue'])
df = df.reset_index(drop=True)
df
'''

"\ndf = df.sort_values(by='DOI', ascending=False)\ndf = df.drop_duplicates(subset=['Title', 'Year', 'Venue'])\ndf = df.reset_index(drop=True)\ndf\n"

In [ ]:
df['Title'].value_counts().head(50)

MOD-DHGN for Autism Segmentation                                                                                                                                   2
Ripplet II transform and higher order cumulants from R-fMRI data for diagnosis of autism                                                                           2
Mobile detection of autism through machine learning on home video: A development and prospective validation study.                                                 2
Hierarchical POMDP Framework for a Robot-Assisted ASD Diagnostic Protocol                                                                                          2
Sensing Technologies for Autism Spectrum Disorder Screening and Intervention.                                                                                      2
Miniature Crane Prototype: A Novel Approach for Recognizing Yoga Postures to Treat Autistic Children                                                               2
Autism Spe

In [ ]:
df[df['Title']=="Concordance between physiological arousal and emotion expression during fear in young children with autism spectrum disorders."]

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year,Database,text
96,Concordance between physiological arousal and ...,This study aimed to measure emotional expressi...,"DIAGNOSIS of autism, TREATMENT of autism, AROU...",NaN,https://search.ebscohost.com/login.aspx?direct...,"Zantinge, Gemma and van Rijn, Sophie and Sto...",Autism: The International Journal of Research ...,2019.0,CINAHL (Exodus),Title: Concordance between physiological arous...
817,Concordance between physiological arousal and ...,This study aimed to measure emotional expressi...,"['arousal', 'autism', 'concordance', 'expressi...",10.1177/1362361318766439,https://pubmed.ncbi.nlm.nih.gov/29595334/,"Zantinge, van Rijn, Stockmann, Swaab",Autism : the international journal of research...,2019.0,PubMed,Title: Concordance between physiological arous...


In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df.sort_values('Title', inplace = True)
df

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year,Database,text
708,"""Mommy Blogs"" and the Vaccination Exemption Na...",Social media offer an unprecedented opportunit...,"['Internet', 'attitudes', 'health knowledge', ...",10.2196/publichealth.6586,https://pubmed.ncbi.nlm.nih.gov/27876690/,"Tangherlini, Roychowdhury, Glenn, Crespi, Band...",JMIR public health and surveillance,2016.0,PubMed,"Title: ""Mommy Blogs"" and the Vaccination Exemp..."
712,"""Sequencing Matters"": Investigating Suitable A...",Social robots have been shown to be promising ...,"['action selection', 'attention skills', 'auti...",10.3389/frobt.2022.784249,https://pubmed.ncbi.nlm.nih.gov/35356059/,"Baraka, Couto, Melo, Paiva, Veloso",Frontiers in robotics and AI,2022.0,PubMed,"Title: ""Sequencing Matters"": Investigating Sui..."
438,"""Um"" and ""Uh"" Usage Patterns in Children with ...","Pragmatic language difficulties, including unu...","['Autism', 'Disfluency', 'Fillers', 'Natural l...",10.1007/s10803-022-05565-4,https://pubmed.ncbi.nlm.nih.gov/35499654/,"Lawley, Bedrick, MacFarlane, Dolata, Salem, Fo...",Journal of autism and developmental disorders,2023.0,PubMed,"Title: ""Um"" and ""Uh"" Usage Patterns in Childre..."
1039,'SenseA'-Autism Early Signs and Pre-Aggressive...,This paper presents an efficient solution for ...,autism early signs; computer vision; feature e...,10.1109/AMS.2017.28,https://www.scopus.com/inward/record.uri?eid=2...,Gamaethige C.; Gunathilake U.; Jayasena D.; Ma...,AMS 2017 - Asia Modelling Symposium 2017 and 1...,2018.0,Scopus,Title: 'SenseA'-Autism Early Signs and Pre-Agg...
888,25th Annual Computational Neuroscience Meeting...,A1 Functional advantages of cell-type heteroge...,NaN,10.1186/s12868-016-0283-6,https://pubmed.ncbi.nlm.nih.gov/27534393/,NaN,BMC neuroscience,2016.0,PubMed,Title: 25th Annual Computational Neuroscience ...
...,...,...,...,...,...,...,...,...,...,...
1467,rs-fMRI Analysis Using Spatio-Temporal Sparse ...,Neuropsychiatric diseases such as Autism Spect...,CNN; Deep Learning; fMRI; Image Processing; Su...,10.1109/SIU55565.2022.9864751,https://www.scopus.com/inward/record.uri?eid=2...,Yener F.M.; Yildiz S.; Hafeez M.A.; Kayasandik...,2022 30th Signal Processing and Communications...,2022.0,Scopus,Title: rs-fMRI Analysis Using Spatio-Temporal ...
469,rs-fMRI and machine learning for ASD diagnosis...,Autism Spectrum Disorder (ASD) diagnosis is st...,NaN,10.1038/s41598-022-09821-6,https://pubmed.ncbi.nlm.nih.gov/35411059/,"Santana, de Carvalho, Rodrigues, Bastos, de So...",Scientific reports,2022.0,PubMed,Title: rs-fMRI and machine learning for ASD di...
1440,sha-Early Intervention for children at risk of...,Autism Spectrum Disorder (ASD) is a developmen...,Autism Spectrum Disorder; CNN; Cognitive devel...,10.1109/I4Tech55392.2022.9952803,https://www.scopus.com/inward/record.uri?eid=2...,Shetty T.; Zope V.; Dandekar M.; Devnani A.; M...,2022 International Conference on Industry 4.0 ...,2022.0,Scopus,Title: sha-Early Intervention for children at ...
1103,‘Autistic Robots’ for Embodied Emulation of Be...,The goal of this work is to enable interaction...,NaN,10.1007/978-3-319-70022-9_11,https://www.scopus.com/inward/record.uri?eid=2...,Baraka K.; Melo F.S.; Veloso M.,Lecture Notes in Computer Science (including s...,2017.0,Scopus,Title: ‘Autistic Robots’ for Embodied Emulatio...


In [ ]:
df.to_csv(f'{main_folder}/autism_ai_behavior_diagnosis_formatted__controlled_combined_noduplicates_semanticallyfiltered.csv', index=False)

In [ ]:
df

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year,Database,text
708,"""Mommy Blogs"" and the Vaccination Exemption Na...",Social media offer an unprecedented opportunit...,"['Internet', 'attitudes', 'health knowledge', ...",10.2196/publichealth.6586,https://pubmed.ncbi.nlm.nih.gov/27876690/,"Tangherlini, Roychowdhury, Glenn, Crespi, Band...",JMIR public health and surveillance,2016.0,PubMed,"Title: ""Mommy Blogs"" and the Vaccination Exemp..."
712,"""Sequencing Matters"": Investigating Suitable A...",Social robots have been shown to be promising ...,"['action selection', 'attention skills', 'auti...",10.3389/frobt.2022.784249,https://pubmed.ncbi.nlm.nih.gov/35356059/,"Baraka, Couto, Melo, Paiva, Veloso",Frontiers in robotics and AI,2022.0,PubMed,"Title: ""Sequencing Matters"": Investigating Sui..."
438,"""Um"" and ""Uh"" Usage Patterns in Children with ...","Pragmatic language difficulties, including unu...","['Autism', 'Disfluency', 'Fillers', 'Natural l...",10.1007/s10803-022-05565-4,https://pubmed.ncbi.nlm.nih.gov/35499654/,"Lawley, Bedrick, MacFarlane, Dolata, Salem, Fo...",Journal of autism and developmental disorders,2023.0,PubMed,"Title: ""Um"" and ""Uh"" Usage Patterns in Childre..."
1039,'SenseA'-Autism Early Signs and Pre-Aggressive...,This paper presents an efficient solution for ...,autism early signs; computer vision; feature e...,10.1109/AMS.2017.28,https://www.scopus.com/inward/record.uri?eid=2...,Gamaethige C.; Gunathilake U.; Jayasena D.; Ma...,AMS 2017 - Asia Modelling Symposium 2017 and 1...,2018.0,Scopus,Title: 'SenseA'-Autism Early Signs and Pre-Agg...
888,25th Annual Computational Neuroscience Meeting...,A1 Functional advantages of cell-type heteroge...,NaN,10.1186/s12868-016-0283-6,https://pubmed.ncbi.nlm.nih.gov/27534393/,NaN,BMC neuroscience,2016.0,PubMed,Title: 25th Annual Computational Neuroscience ...
...,...,...,...,...,...,...,...,...,...,...
1467,rs-fMRI Analysis Using Spatio-Temporal Sparse ...,Neuropsychiatric diseases such as Autism Spect...,CNN; Deep Learning; fMRI; Image Processing; Su...,10.1109/SIU55565.2022.9864751,https://www.scopus.com/inward/record.uri?eid=2...,Yener F.M.; Yildiz S.; Hafeez M.A.; Kayasandik...,2022 30th Signal Processing and Communications...,2022.0,Scopus,Title: rs-fMRI Analysis Using Spatio-Temporal ...
469,rs-fMRI and machine learning for ASD diagnosis...,Autism Spectrum Disorder (ASD) diagnosis is st...,NaN,10.1038/s41598-022-09821-6,https://pubmed.ncbi.nlm.nih.gov/35411059/,"Santana, de Carvalho, Rodrigues, Bastos, de So...",Scientific reports,2022.0,PubMed,Title: rs-fMRI and machine learning for ASD di...
1440,sha-Early Intervention for children at risk of...,Autism Spectrum Disorder (ASD) is a developmen...,Autism Spectrum Disorder; CNN; Cognitive devel...,10.1109/I4Tech55392.2022.9952803,https://www.scopus.com/inward/record.uri?eid=2...,Shetty T.; Zope V.; Dandekar M.; Devnani A.; M...,2022 International Conference on Industry 4.0 ...,2022.0,Scopus,Title: sha-Early Intervention for children at ...
1103,‘Autistic Robots’ for Embodied Emulation of Be...,The goal of this work is to enable interaction...,NaN,10.1007/978-3-319-70022-9_11,https://www.scopus.com/inward/record.uri?eid=2...,Baraka K.; Melo F.S.; Veloso M.,Lecture Notes in Computer Science (including s...,2017.0,Scopus,Title: ‘Autistic Robots’ for Embodied Emulatio...


In [ ]:
removed_rows = original_data[~original_data.index.isin(df2.index)]

# Check if there are removed rows
if not removed_rows.empty:
    # Randomly select one removed row and print it
    random_entry = removed_rows.sample()
    print(random_entry["Title"].values)
    print(random_entry["Abstract"].values)
    print(random_entry["Keywords"].values)
else:
    print("No entries were removed.")

['Exploratory Study of Parenting Differences for Autism Spectrum Disorder and Attachment Disorder.']
['The current study explored similarities and differences in parenting stress (PSI) and behaviours in parent reports of autism spectrum disorder (ASD) and attachment disorder (AD). 155 parents whose children had developmental delays and disorders completed the social communication questionnaire, Randolph attachment questionnaire, strengths and difficulties questionnaire, PSI, and parent-child relationship inventory. Parents of children with AD reported greater levels of PSI than parents of children with ASD. Parents of children reaching criteria for both disorders reported the greatest levels of PSI. Limit setting was poorest in parents of children with both classifications, followed by parents of children with AD, and then ASD. Limit setting mediated the relationship between PSI and child behaviour problems for parents of children with ASD\u2009<\u2009but not for parents of children wi

In [ ]:
for filter_words in [autism_sigle]:

  removed_rows = removed_rows[
      removed_rows['Title'].str.contains('|'.join(fr'\b{word}\b' for word in filter_words), case=False) |
      removed_rows['Abstract'].str.contains('|'.join(fr'\b{word}\b' for word in filter_words), case=False) |
      removed_rows['Keywords'].str.contains('|'.join(fr'\b{word}\b' for word in filter_words), case=False)
  ]
  print(len(removed_rows))

4


In [ ]:
removed_rows.to_csv(f'{main_folder}/sciencedirect/unrelated_acronyms_formatted.csv', index=False)

In [ ]:
removed_rows.shape

In [ ]:
# Check if there are removed rows
if not df.empty:
    # Randomly select one removed row and print it
    random_entry = df.sample()
    print(random_entry["Title"].values)
    print(random_entry["Abstract"].values)
    print(random_entry["Keywords"].values)
else:
    print("No entries were removed.")